version: 0.2

env:
  git-credential-helper: yes
  secrets-manager:
    ESWITCH_ARTIFACOTRY_USERNAME: "aws/artifactory:username"
    ESWITCH_ARTIFACOTRY_PASSWORD: "aws/artifactory:password"
    SIMPLEJAVAMAIL_SMTP_HOST: "aws/simplejavamail:simplejavamail.smtp.host"
    SIMPLEJAVAMAIL_IMAP_HOST: "aws/simplejavamail:simplejavamail.imap.host"
    SIMPLEJAVAMAIL_SMTP_USERNAME: "aws/simplejavamail:simplejavamail.smtp.username"
    SIMPLEJAVAMAIL_SMTP_PASSWORD: "aws/simplejavamail:simplejavamail.smtp.password"
    SIMPLEJAVAMAIL_DEFAULTS_FROM_ADDRESS: "aws/simplejavamail:simplejavamail.defaults.from.address"
    SIMPLEJAVAMAIL_DEFAULTS_TO_ADDRESS: "aws/simplejavamail:simplejavamail.defaults.to.address"

phases:
  install:
    commands:
      - echo $(date +"%F %T.%N") install phase started
      - yum update -y
      - yum -y install ant
      - # install latest maven
      - # yum install -y maven # resolves to outdated maven 3.0
      - maven_version=3.9.1
      - wget -q https://dlcdn.apache.org/maven/maven-3/${maven_version}/binaries/apache-maven-${maven_version}-bin.tar.gz
      - tar -xf apache-maven-${maven_version}-bin.tar.gz
      - mv apache-maven-${maven_version} /usr/local/apache-maven
      - export M2_HOME=/usr/local/apache-maven
      - export M2=$M2_HOME/bin
      - export PATH=$M2:$PATH
      - mvn --version
    finally:
      - echo $(date +"%F %T.%N") install phase ended
  pre_build:
    commands:
      - echo $(date +"%F %T.%N") pre_build phase started
    finally:
      - echo $(date +"%F %T.%N") pre_build phase ended
  build:
    commands:
      - echo $(date +"%F %T.%N") build phase started
      - pwd
      - echo ESWITCH_ARTIFACOTRY_USERNAME $ESWITCH_ARTIFACOTRY_USERNAME
      - echo SIMPLEJAVAMAIL_SMTP_HOST $SIMPLEJAVAMAIL_SMTP_HOST
      - echo SIMPLEJAVAMAIL_SMTP_USERNAME $SIMPLEJAVAMAIL_SMTP_USERNAME
      - mvn --no-transfer-progress -s settings.xml clean deploy
    finally:
      - echo $(date +"%F %T.%N") build phase ended
  post_build:
    commands:
      - echo $(date +"%F %T.%N") post_build phase started
      - cd $CODEBUILD_SRC_DIR
      - ls -a
      - git config user.name
      - git config user.email
      - git status
      - git add README.md
      - git status
      - git commit -m "README.md"
      - git status
      - git push
    finally:
      - echo $(date +"%F %T.%N") post_build phase ended

artifacts:
  files:
    - '*.jar'
  base-directory: target
  name: jar